name: staged-deployment

on:
  push:
    branches:
      - main
  
  workflow_dispatch: {}

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up prerequisites
      run: |
        sudo apt-get update
        sudo apt-get -y install unzip
        
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.7
        
  authenticate:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: Set up Azure CLI authentication
      run: |
        az login --service-principal --username "${{ env.ARM_CLIENT_ID }}" --password="${{ env.ARM_CLIENT_SECRET }}" --tenant "${{ env.ARM_TENANT_ID }}"

  terraform-init:
    runs-on: ubuntu-latest
    needs: authenticate
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
   
    - name: Create backend config file
      run: |
        cat <<EOF > backend-config.tfvars
        resource_group_name = "rg-storage-tfstate"
        storage_account_name = "tfstorage005"
        container_name       = "tfstate"
        key                  = "project.tfstate"
        EOF
    
    - name: Terraform Init
      run: terraform init -backend-config=backend-config.tfvars

  terraform-validate:
    runs-on: ubuntu-latest
    needs: terraform-init
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Terraform Validate
      run: terraform validate

  terraform-plan:
    runs-on: ubuntu-latest
    needs: terraform-validate
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Terraform Plan
      run: terraform plan -var-file=configuration.tfvars -out=tfplan

  # terraform-apply:
  #   runs-on: ubuntu-latest
  #   needs: terraform-plan
  #   steps:
  #   - name: Checkout repository
  #     uses: actions/checkout@v2

  #   - name: Terraform Apply
  #     run: terraform apply tfplan
